server.port=8085
spring.application.name=Hen

spring.r2dbc.url=r2dbc:pool:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
spring.r2dbc.username=postgres.tuuxndxyhvjrnvqkgrma
spring.r2dbc.password=UpfA3yGIo7CFFLyK