server:
  port: 8080

spring:
  application:
    name: foods   
  r2dbc:
    url: r2dbc:pool:postgresql://food_owner:npg_xpMTt67ugfvJ@ep-summer-mountain-a440nkjh-pooler.us-east-1.aws.neon.tech/food?sslmode=require
    username: food_owner
    password: npg_xpMTt67ugfvJ
  #security:
    #oauth2:
      #resourceserver:
        #jwt:
          #issuer-uri: http://localhost:8080/realms/PRS

    #url: ${DATABASE_URL}
    #username: ${DATABASE_USERNAME}
    #password: ${DATABASE_PASSWORD}

    
